name: Cours de M. H. - Méthodo et culture générale
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e4fdfe'
    - '#fcacc5'
    - '#c16a6a'
    - '#91493b'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
