layout_spectrum: 0.7446458862754194
typography_spectrum: 0.28443969245096395
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6397034204714369
  lightness: 0.32007803046771577
  saturation: 0.036679780569185715
  rhythmicContrast: 0.9983257106045206
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Cours de M. H.
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Facebook, trombinoscope du consommateur.'
    id: 3a134fc1-1c5d-44a6-95e2-0ba4e86cc162
    type: content
  - name: Joseph Campbell
    id: 80a2969c-d155-4166-8fbd-7d6cfe94e467
    type: content
favicon: null
title: Méthodo et culture générale
content: []
description: >-
  Cours libre de Julien Horville à l'intention de la classe de 1ère L de l'École
  Diagonale.
purpose:
  - type: external
    url: 'http://www.ecole-diagonale.fr'
    label: Ecole Diagonale
