layout_spectrum: 0.3227975534264109
typography_spectrum: 0.41803588642416023
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.5290521247365909
  lightness: 0.25099892654493083
  saturation: 0.14543624783709352
  rhythmicContrast: 0.5215272522128491
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Cours de M. H.
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Facebook, trombinoscope du consommateur.'
    id: 3a134fc1-1c5d-44a6-95e2-0ba4e86cc162
    type: content
  - name: Joseph Campbell
    id: 80a2969c-d155-4166-8fbd-7d6cfe94e467
    type: content
favicon: null
title: Méthodo et culture générale
content: []
description: >-
  Cours libre de Julien Horville à l'intention de la classe de 1ère L de l'École
  Diagonale.
purpose:
  - type: external
    url: 'http://www.ecole-diagonale.fr'
    label: Ecole Diagonale
